stages:
  - build
  - test
  - deploy


deploy:
  image: alpine
  stage: deploy
  variables:
    INSTANCE: "ec2-user@ec2-54-165-224-235.compute-1.amazonaws.com"
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - SSH_PRIVATE_KEY='ff'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no "$INSTANCE" "cd project; docker-compose down; docker rm -f $(docker ps -a -q); docker-compose up -d"
