stages:
  - build
  - test
  - deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

test:
  stage: test
  image:
    name: registry.gitlab.com/ensae-dev/projects_2022_2023/data-solution
    entrypoint: [""]
  services:
    - postgres:12.2-alpine
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: fastapi_db
    POSTGRES_HOST_AUTH_METHOD: trust
    # Variable used to allow project to connect to gitlab-ci service
    DB_URI: "postgresql://postgres:postgres@postgres:5432/fastapi_db"
  script:
    - pip install pytest
    - pytest .


deploy:
  image: alpine
  stage: deploy
  variables:
    SSH_PRIVATE_KEY: "fdzefde"
    INSTANCE: "fzefzef"
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $INSTANCE "cd ~; touch test.txt"
