stages:
  - build
  - test

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
services:
  - postgres:12.2-alpine

variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  # Variable used to allow project to connect to gitlab-ci service
  DB_URI: "postgresql://postgres:postgres@postgres:5432/fastapi_db"

test:
  stage: test
  image:
    name: registry.gitlab.com/ensae-dev/projects_2022_2023/data-solution
    entrypoint: [""]
  script:
    - pip install pytest
    - pytest .
