stages:
  - build
  - test

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/build:${CI_COMMIT_TAG}"
test:
  stage: test
  image:
    name: "${CI_REGISTRY_IMAGE}/build:${CI_COMMIT_TAG}"
    entrypoint: [""]
  script:
    - pip install pytest
    - pytest
