stages:
  - build
  - test
  - deploy


deploy:
  image: alpine
  stage: deploy
  variables:
    INSTANCE: "ec2-user@ec2-54-165-224-235.compute-1.amazonaws.com"
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - SSH_PRIVATE_KEY='-----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEAllQ5yG4MtA/q9hCq+OQlrh0QgdkN1FrxB6+4ONBDr8aqRIBDEBf2YslnwgXZfX2xuxhIpzzDT3JknwD4ioy3hvh67/IXJ98DqkUP8o/fUc/qgreD14Qjp+LUvnX/UPP9GaWNI3kNrd9i/AadiWy6gewcwAwGbsHIS89xYprPcdVJrXav+00M7kFLG3GUw/VD59P3ahXPuD2R7e8cOtPX9k46LymzkmhILq5Ruz71iauEcxK4yT32lbzQn92r6JBiSgTs1qI9WY9h0c+kASSLhc9fxzU/dQ3wxLoBxQ1LYCb5Iu5y3QPqG42dY73z/TJAwa8D7Q5WvkzHtXOTDPPnjwIDAQABAoIBAEUOEbERZIJ+YWeBRpiobOqrbT7Ij0LCN8BZJt3qRX2EXAi1hpjo+QRuElydRUgRKkiQoic4kVt4Z+JmlsVGWLQGhqqcYaiuGEfqC6ZYErTJNqevVz/z8lEXsLSBDbSJL/XNB6WI4RDC8fxlqY5MROyToq1RmM7d831noGU0SiC2rTmEowUc4XmFT+IDfCZ8cLzKtdWnSuyWjbiKNEUmr+HMQaLYc54gPCBKV3HPPGCPOrdSenuc60FG4D0JGIH+VoNHQfRpoE1Bq0aSHX70D4FxVmW9HWGJpPKzlSPLszAptTb/Ub5QolDgRLIWr+DMACfv6HE/aDzsUpDlWlj9LoECgYEA2a6+ynhypcvNtlBVZo9tMfYjHgz+a6hGsIqxEVxc1RzDLVbTSoJlvdzcP6q6TQUeKCDX0ErdmZKJ6OfesYOvq4Sx+LSEkW0ZvFhJIXeSgpFuiSwttzf0qronR+9ryWVU8aYp/tdTWDG1vTVhKenQ98DtDdPGgQ0F4Sc97w7eUE8CgYEAsMphSqVwIPWul7Ln4dONQWADKIdeux1LPeFVfQjwyl1sgpoFyuiA6xGbLHvcioTYO3NBnoDY+Hkd43EzcMWBUzkGjA1nnv2g5kdEGLFe9Wi75Vmh8o/QD+4dnbft5TwPinY9mOfDL/tjwSyOc1OgIq2KilK7ZOX4BG9pCLs95MECgYB2Vfub/8x7ewZyhMtYPMIkteSzUmcAyXLcSBkoEejZZZBo1ll4mNiMVUNaTQqIEi8pq2kG75v1/2Z/OYWjRK479J/3TtL+Z6vk6q2exuzblAneAik7/+w+34G5JluXGUILN8R+qDnDqQpeOGWArn4OIU/9A1JXF2hJ1NZjXdbXGwKBgQCvdp2rbZllTRIUw977NnFLAlUAI6L0yXVFHGExsO7zmle5I889/Rb+t8GwG9rerEzEbHcjLrSpn+P3OgIZGh1qEP4bgK5okUfhZbgDXf9mSKW8UwK18OBK/0TrpYJ6curlvMcT/GqwM6xlLKjRc51K7bzD3qrY0JohJMY1gUlDwQKBgCaTNn035duR6cJG1VuwUlQ2njBnFcy+jTmMa5qUDIEdDb1MeXoyOnZhMVOKnamT1X5Hj294QzLlwZe4UQXP7hp8AZqEoSeqOOzE+W0mCj6WrzVUvpVA8pEqdxp7WHT1ehYRuHK2EICGt/5P3jS+u3uN6kghpx2s/DL28cz9RjWm-----END RSA PRIVATE KEY-----'
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no "$INSTANCE" "cd project; docker-compose down; docker rm -f $(docker ps -a -q); docker-compose up -d"
