version: "3.8"

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"


  db:
    image: postgres:12
    env_file:
      - .env
    volumes: 
      - vol_1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5432
    ports:
      - "5432:5432"

volumes:
   vol_1:

