version: "3.8"

services:
  app:
    build: .
    depends_on :
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"


  db:
    image: postgres:12
    env_file:
      - .env
    volumes: 
      - vol1:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
   vol1:

